name: pr

on:
  push:
    branches-ignore:
      - main
    tags-ignore:
      - '*'

jobs:
  check_pr:
    runs-on: ubuntu-latest
    outputs:
      hasOpenPR: ${{ steps.check_pr.outputs.hasOpenPR }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check existing PR for current branch
        id: check_pr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          branch=$(git rev-parse --abbrev-ref HEAD)
          pr_count=$(gh pr list --state open --head "$branch" --json number --jq 'length')
          echo "::set-output name=hasOpenPR::$( [ $pr_count -gt 0 ] && echo true || echo false )"

  create_pr:
    runs-on: ubuntu-latest
    needs: check_pr
    if: ${{ needs.check_pr.outputs.hasOpenPR == 'false' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Spice
        run: |
          curl https://install.spiceai.org | /bin/bash

      - name: Add Spice to PATH
        run: |
          echo "$HOME/.spice/bin" >> $GITHUB_PATH

      - name: Run Spice
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "$HOME/.spice/bin" >> $GITHUB_PATH
          spice i ai
          spice run &> spice.log &
          sleep 5

      - name: Wait for Spice runtime to be ready
        run: |
          bash -c 'while [[ "$(curl -s http://localhost:8090/health)" != "ok" ]]; do sleep 1; done' || false
        timeout-minutes: 1

      - name: Stop spice and check logs
        if: always()
        run: |
          killall spice || true
          cat spice.log
