name: pr

on:
  push:
     branches-ignore:
      - main

jobs:
  check_pr:
    runs-on: ubuntu-latest
    outputs:
      hasOpenPR: ${{ steps.check_pr.outputs.hasOpenPR }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check existing PR for current branch
        id: check_pr
        run: |
          branch=$(git rev-parse --abbrev-ref HEAD)
          pr_count=$(gh pr list --state open --head "$branch" --json number --jq 'length')
          echo "::set-output name=hasOpenPR::$( [ $pr_count -gt 0 ] && echo true || echo false )"

  create_pr:
    runs-on: ubuntu-latest
    needs: check_pr
    if: ${{ needs.check_pr.outputs.hasOpenPR == 'false' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Install Spice
      #   run: |
      #     curl https://install.spiceai.org | /bin/bash

      # - name: Run Spicepod
      #   run: |
      #     spicepod run -f .github/workflows/spicepod.yaml